name: centernet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - cudatoolkit=11.1
  - pytorch>=1.6.0
  - torchvision
  - numpy
  - scipy
  - filterpy
  - cython
  - pip:
    - pytorch-lightning
    - opencv-python
    - albumentations>=1.0.0
    - git+https://github.com/gautamchitnis/cocoapi.git@cocodataset-master#subdirectory=PythonAPI
    - git+https://github.com/gau-nernst/TrackEval.git
