model:
  task: tracking

  backbone:
    name: resnet34
    pretrained: True
  
  neck:
    name: fpn
    upsample_channels: [256, 128, 64]
    upsample_type: nearest
    conv_type: normal

  output_heads:
    heatmap:
      num_classes: 1
      init_bias: -2.19
      target_method: cornernet
      loss_function: cornernet_focal
      loss_weight: 1

    box_2d:
      init_bias: 10
      loss_function: giou
      loss_weight: 5

    reid:
      init_bias: null
      loss_function: ce
      max_track_ids: 70000
      loss_weight: 1

  optimizer:
    name: Adam
    params:
      lr: 0.0001
      weight_decay: 0.0001

  lr_scheduler:
    name: OneCycleLR
    params:
      max_lr: 0.0001

data:
  train:
    dataset:
      type: crowdhuman
      data_dir: datasets/CrowdHuman
      split: train_3000
      detection_for_tracking: True

      transforms:
        HorizontalFlip:
          p: 0.5
        MotionBlur:
          blur_limit: [3, 15]
        Affine:
          scale: [0.8, 1.25]
          rotate: [-10, 10]
        RandomResizedCrop:
          width: 608
          height: 608
        ColorJitter:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
        Cutout:
          num_holes: 10
          max_w_size: 60
          max_h_size: 60
  
    dataloader:
      batch_size: 16
      num_workers: 8
      shuffle: True
      pin_memory: True

  validation:
    dataset:
      type: crowdhuman
      data_dir: datasets/CrowdHuman
      split: val_800
      
      transforms:
        Resize:
          width: 608
          height: 608
    
    dataloader:
      batch_size: 32
      num_workers: 8
      shuffle: False
      pin_memory: True

trainer:
  gpus: 1
  precision: 16
  max_epochs: 60
  val_check_interval: 1.0
  benchmark: True
  gradient_clip_val: 35

  logger:
    name: WandbLogger
    params:
      project: crowdhuman_tracking
      log_model: True

  callbacks:
    - name: ModelCheckpoint
      params:
        monitor: val/total_loss
        save_last: True

    - name: LearningRateMonitor
      params:
        logging_interval: step
    
    - name: LogImageCallback
      params:
        n_epochs: 5
        random: True
